# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
---

version: 2.1
# Use a package of configuration called an orb.
#

workflows:
    deploy:
        jobs:
            - build:
                  context:
                      - dockerhub-login-naomi

jobs:
    build:
      docker:
            - image: nixos/nix
      steps:
            - add_ssh_keys:
                  fingerprints:
                  - "wDuQH8vckKgm5eiqS8gOOKhxzMOYus2VzcM/LbGwAL0"

            - run:
                  name: Enable Nix flakes
                  command: | 
                        nix-env -iA nixpkgs.nixFlakes
                        mkdir -p ~/.config/nix
                        echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf

            - checkout

            - run:
                  name: Build site executable
                  command: nix build -v 

            - run:
                  name: static site generator go brrrrrrr
                  command: ./result/bin/nliu-exe clean && ./result/bin/nliu-exe build

            - store_artifacts:
                  path: _site
                  destination: built_site
            - deploy:
                  name: Deploy to Github Pages (repo hosting main site)
                  command: |
                        # if [ "${CIRCLE_BRANCH}" == "main" ]; then
                              sh .circleci/deploy.sh
                        # fi
