# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
---

version: 2.1
# Use a package of configuration called an orb.
#

workflows:
    deploy:
        jobs:
            context:
                - dockerhub-login-norman

jobs:
    build:
        docker:
            - image: fpco/stack-build
              auth:
                  username: $DOCKERHUB_USER
                  password: $DOCKERHUB_PASSWORD
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "wDuQH8vckKgm5eiqS8gOOKhxzMOYus2VzcM/LbGwAL0"

            - checkout

            - restore_cache:
                  name: Restore Cached Dependencies
                  keys:
                      - v1-stack-work-{{ checksum "stack.yaml" }}

            - run:
                  name: Resolve/Update Dependencies
                  command: stack --no-terminal-setup

            - run:
                  name: Build the site generator executable
                  command: stack build

            - save_cache:
                  name: Cache Dependencies
                  key: v1-stack-work-{{ checksum "stack.yaml" }}
                  paths:
                      - "~/.stack"
                      - "~/.stack-work"

            - run:
                  name: Build site
                  command: stack exec site build

            - store_artifacts:
                  path: _site
                  destination: built_site
            - deploy:
                  name: Deploy to Github Pages (repo hosting main site)
                  command: |
                    if [ "${CIRCLE_BRANCH}" == "main" ]; then
                        .circleci/deploy.sh
                    fi
